#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-activejob
Version  : 4.2.3
Release  : 3
URL      : https://rubygems.org/downloads/activejob-4.2.3.gem
Source0  : https://rubygems.org/downloads/activejob-4.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-globalid
BuildRequires : rubygem-rdoc

%description
# Active Job -- Make work happen later
Active Job is a framework for declaring jobs and making them run on a variety
of queueing backends. These jobs can be everything from regularly scheduled
clean-ups, to billing charges, to mailings. Anything that can be chopped up into
small units of work and run in parallel, really.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n activejob-4.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-activejob.gemspec

%build
gem build rubygem-activejob.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
activejob-4.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/activejob-4.2.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/cdesc-Arguments.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/deserialize_argument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/deserialize_global_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/deserialize_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/serialize_argument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/serialize_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/serialize_hash_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/serialized_global_id%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Arguments/transform_symbol_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/after_enqueue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/after_perform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/around_enqueue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/around_perform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/before_enqueue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/before_perform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Callbacks/cdesc-Callbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/ConfiguredJob/cdesc-ConfiguredJob.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/ClassMethods/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/ClassMethods/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/cdesc-Core.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/deserialize_arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/deserialize_arguments_if_needed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Core/serialize_arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/DeserializationError/cdesc-DeserializationError.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/DeserializationError/original_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Enqueuing/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Enqueuing/ClassMethods/job_or_instantiate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Enqueuing/ClassMethods/perform_later-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Enqueuing/cdesc-Enqueuing.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Enqueuing/enqueue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Enqueuing/retry_job-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Execution/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Execution/ClassMethods/perform_now-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Execution/cdesc-Execution.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Execution/perform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Execution/perform_now-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Logging/ActiveSupport/cdesc-ActiveSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Logging/LogSubscriber/cdesc-LogSubscriber.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Logging/cdesc-Logging.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapter/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapter/ClassMethods/load_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapter/ClassMethods/queue_adapter%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapter/cdesc-QueueAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/BackburnerAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/BackburnerAdapter/cdesc-BackburnerAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/DelayedJobAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/DelayedJobAdapter/cdesc-DelayedJobAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/InlineAdapter/cdesc-InlineAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QuAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QuAdapter/cdesc-QuAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QueAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QueAdapter/cdesc-QueAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QueueClassicAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QueueClassicAdapter/build_queue-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/QueueClassicAdapter/cdesc-QueueClassicAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/ResqueAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/ResqueAdapter/cdesc-ResqueAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/SidekiqAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/SidekiqAdapter/cdesc-SidekiqAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/SneakersAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/SneakersAdapter/cdesc-SneakersAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/SuckerPunchAdapter/JobWrapper/cdesc-JobWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/SuckerPunchAdapter/cdesc-SuckerPunchAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/TestAdapter/cdesc-TestAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/TestAdapter/enqueued_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/TestAdapter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/TestAdapter/perform_enqueued_at_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/TestAdapter/perform_enqueued_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/TestAdapter/performed_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueAdapters/cdesc-QueueAdapters.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueName/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueName/ClassMethods/queue_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueName/cdesc-QueueName.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/QueueName/queue_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Railtie/ActiveSupport/cdesc-ActiveSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/SerializationError/cdesc-SerializationError.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/after_teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/assert_enqueued_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/assert_enqueued_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/assert_no_enqueued_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/assert_no_performed_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/assert_performed_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/assert_performed_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/before_setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/cdesc-TestHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/clear_enqueued_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/clear_performed_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/perform_enqueued_jobs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/queue_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/TestHelper/serialize_args_for_assertion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/cdesc-ActiveJob.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/gem_version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/ActiveJob/version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/Rails/Generators/JobGenerator/cdesc-JobGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/Rails/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/activejob-4.2.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/arguments.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/callbacks.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/configured_job.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/core.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/enqueuing.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/execution.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/gem_version.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/logging.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/backburner_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/delayed_job_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/inline_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/qu_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/que_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/queue_classic_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/resque_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/sidekiq_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/sneakers_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/sucker_punch_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_adapters/test_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/queue_name.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/railtie.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/test_case.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/active_job/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/rails/generators/job/job_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/activejob-4.2.3/lib/rails/generators/job/templates/job.rb
/usr/lib64/ruby/gems/2.2.0/specifications/activejob-4.2.3.gemspec
